// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeU_7vAlPngtWSTIWyzYsaBrxYF65eKlQ',
    appId: '1:376229608727:web:bab31cc66105e0dd9fcb52',
    messagingSenderId: '376229608727',
    projectId: 'login-signup-7b3b9',
    authDomain: 'login-signup-7b3b9.firebaseapp.com',
    storageBucket: 'login-signup-7b3b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeCanWs0ODy_G6B8lXeGAPoWt89zhR9NU',
    appId: '1:376229608727:android:1e93b73105d9b1519fcb52',
    messagingSenderId: '376229608727',
    projectId: 'login-signup-7b3b9',
    storageBucket: 'login-signup-7b3b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtiMxyRYONwqajJVejFN2D3Eq3minHfkA',
    appId: '1:376229608727:ios:f94c65f030e0f2b89fcb52',
    messagingSenderId: '376229608727',
    projectId: 'login-signup-7b3b9',
    storageBucket: 'login-signup-7b3b9.appspot.com',
    iosBundleId: 'com.example.fireYoutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtiMxyRYONwqajJVejFN2D3Eq3minHfkA',
    appId: '1:376229608727:ios:f94c65f030e0f2b89fcb52',
    messagingSenderId: '376229608727',
    projectId: 'login-signup-7b3b9',
    storageBucket: 'login-signup-7b3b9.appspot.com',
    iosBundleId: 'com.example.fireYoutube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeU_7vAlPngtWSTIWyzYsaBrxYF65eKlQ',
    appId: '1:376229608727:web:e804be058166cd0c9fcb52',
    messagingSenderId: '376229608727',
    projectId: 'login-signup-7b3b9',
    authDomain: 'login-signup-7b3b9.firebaseapp.com',
    storageBucket: 'login-signup-7b3b9.appspot.com',
  );
}
